//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsLibClient.CalcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcServiceReference.ICalcService", CallbackContract=typeof(EventsLibClient.CalcServiceReference.ICalcServiceCallback))]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Calculate", ReplyAction="http://tempuri.org/ICalcService/CalculateResponse")]
        void Calculate(int nOp, double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Calculate", ReplyAction="http://tempuri.org/ICalcService/CalculateResponse")]
        System.Threading.Tasks.Task CalculateAsync(int nOp, double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SuscribeCalculatedEvents", ReplyAction="http://tempuri.org/ICalcService/SuscribeCalculatedEventsResponse")]
        void SuscribeCalculatedEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SuscribeCalculatedEvents", ReplyAction="http://tempuri.org/ICalcService/SuscribeCalculatedEventsResponse")]
        System.Threading.Tasks.Task SuscribeCalculatedEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SuscribeCalculationFinishedEvent", ReplyAction="http://tempuri.org/ICalcService/SuscribeCalculationFinishedEventResponse")]
        void SuscribeCalculationFinishedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SuscribeCalculationFinishedEvent", ReplyAction="http://tempuri.org/ICalcService/SuscribeCalculationFinishedEventResponse")]
        System.Threading.Tasks.Task SuscribeCalculationFinishedEventAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalcService/Calculated")]
        void Calculated(int nOp, double dblNum1, double dblNum2, double dblResult);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICalcService/CalculationFinished")]
        void CalculationFinished();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : EventsLibClient.CalcServiceReference.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.DuplexClientBase<EventsLibClient.CalcServiceReference.ICalcService>, EventsLibClient.CalcServiceReference.ICalcService {
        
        public CalcServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CalcServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CalcServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Calculate(int nOp, double dblNum1, double dblNum2) {
            base.Channel.Calculate(nOp, dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task CalculateAsync(int nOp, double dblNum1, double dblNum2) {
            return base.Channel.CalculateAsync(nOp, dblNum1, dblNum2);
        }
        
        public void SuscribeCalculatedEvents() {
            base.Channel.SuscribeCalculatedEvents();
        }
        
        public System.Threading.Tasks.Task SuscribeCalculatedEventsAsync() {
            return base.Channel.SuscribeCalculatedEventsAsync();
        }
        
        public void SuscribeCalculationFinishedEvent() {
            base.Channel.SuscribeCalculationFinishedEvent();
        }
        
        public System.Threading.Tasks.Task SuscribeCalculationFinishedEventAsync() {
            return base.Channel.SuscribeCalculationFinishedEventAsync();
        }
    }
}
